services:
  DB:
    container_name: DB
    image: mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql

  API:
    build:
      context: ./API
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=3306
      - VUE_HOST=${VUE_HOST}
    depends_on:
      - db
  
  FRONT:
    container_name: FRONT
    build:
      context: ./FRONT
      dockerfile: Dockerfile
      args:
        VUE_APP_API_HOST: ${API_HOST}
    restart: unless-stopped
    working_dir: /app
    env_file: .env
    ports:
      - 5000:80
    depends_on: 
      - API