apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: API_HOST
              valueFrom:
                configMapKeyRef:
                  key: API_HOST
                  name: env
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DB_DATABASE
                  name: env
            - name: DB_HOST
              value: db
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: env
            - name: DB_PORT
              value: "3306"
            - name: DB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_ROOT_PASSWORD
                  name: env
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: env
            - name: FRONT_HOST
              valueFrom:
                configMapKeyRef:
                  key: FRONT_HOST
                  name: env
            - name: JWT_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: JWT_SECRET_KEY
                  name: env
            - name: TMDB_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: TMDB_API_KEY
                  name: env
            - name: TMDB_FULL_KEY
              valueFrom:
                configMapKeyRef:
                  key: TMDB_FULL_KEY
                  name: env
          image: api
          name: api
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
