apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: API_HOST
              valueFrom:
                configMapKeyRef:
                  key: API_HOST
                  name: env
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DB_DATABASE
                  name: env
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: env
            - name: DB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_ROOT_PASSWORD
                  name: env
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: env
            - name: FRONT_HOST
              valueFrom:
                configMapKeyRef:
                  key: FRONT_HOST
                  name: env
            - name: JWT_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: JWT_SECRET_KEY
                  name: env
            - name: MYSQL_ROOT_PASSWORD
            - name: TMDB_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: TMDB_API_KEY
                  name: env
            - name: TMDB_FULL_KEY
              valueFrom:
                configMapKeyRef:
                  key: TMDB_FULL_KEY
                  name: env
          image: mysql
          name: db
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: db-cm0
            - mountPath: /var/lib/mysql
              name: db-claim1
      restartPolicy: Always
      volumes:
        - configMap:
            name: db-cm0
          name: db-cm0
        - name: db-claim1
          persistentVolumeClaim:
            claimName: db-claim1
